import json
import os
import tempfile
import threading
import time
import unittest
from http.server import BaseHTTPRequestHandler, HTTPServer

from ledger_sdk import Ledger, LedgerError
from ledger_sdk import actor_chain, vocab


class _H(BaseHTTPRequestHandler):
    seen = []
    fail_times = 0  # class-level: number of POSTs to fail with 503 before succeeding
    lock = threading.Lock()

    def do_POST(self):
        body = json.loads(self.rfile.read(int(self.headers["Content-Length"])))
        with _H.lock:
            _H.seen.append((self.path, self.headers.get("Authorization"), body))
            if _H.fail_times > 0:
                _H.fail_times -= 1
                self.send_response(503)
                self.end_headers()
                self.wfile.write(b'{"error":"unavailable"}')
                return
        if body["actor_chain"][0]["id"] == "bad":
            self.send_response(400)
            self.end_headers()
            self.wfile.write(b'{"error":"x"}')
            return
        self.send_response(201)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(json.dumps({"id": "u", "chain": body["chain"], "seq": 1, "hash": "h",
                                      "prev_hash": "", "created_at": "t",
                                      "idempotency_key": body.get("idempotency_key")}).encode())

    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(b'{"ok":true}')

    def log_message(self, *a):
        pass


def _server():
    srv = HTTPServer(("127.0.0.1", 0), _H)
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    return srv


def _tmp_spool():
    fd, path = tempfile.mkstemp(prefix="ledger-sdk-test-", suffix=".jsonl")
    os.close(fd)
    os.unlink(path)  # Ledger/Spool creates it on first write
    return path


class SDKTest(unittest.TestCase):
    def setUp(self):
        _H.seen = []
        _H.fail_times = 0

    def test_noop_without_url(self):
        self.assertIsNone(Ledger("gate", url="").record("t", {}, [{"kind": "human", "id": "a"}]))

    def test_requires_human_first(self):
        with self.assertRaises(ValueError):
            Ledger("gate", url="").record("t", {}, [{"kind": "agent", "id": "a"}])

    def test_posts_contract_body_and_flushes(self):
        srv = _server()
        try:
            l = Ledger("gate", url="http://127.0.0.1:%d" % srv.server_port, token="tok",
                       spool_path=_tmp_spool(), flush_on_exit=False)
            queued = l.record("gate.run.started", {"a": 1}, [{"kind": "human", "id": "alice"}], goal_id="g1")
            self.assertIn("idempotency_key", queued)
            self.assertTrue(l.flush(timeout=5))
            self.assertEqual(l.pending(), 0)
            path, auth, body = _H.seen[-1]
            self.assertEqual(path, "/v1/records")
            self.assertEqual(auth, "Bearer tok")
            self.assertEqual(body["goal_id"], "g1")
            self.assertEqual(body["idempotency_key"], queued["idempotency_key"])
            l.close()
        finally:
            srv.shutdown()

    def test_idempotency_key_autogenerated_and_unique(self):
        l = Ledger("gate", url="")
        # disabled client still validates but returns None; test the key-generating path via
        # a real (but not-yet-flushed) enqueue against an enabled client instead.
        srv = _server()
        try:
            l = Ledger("gate", url="http://127.0.0.1:%d" % srv.server_port,
                       spool_path=_tmp_spool(), flush_on_exit=False)
            b1 = l.record("t", {}, [{"kind": "human", "id": "a"}])
            b2 = l.record("t", {}, [{"kind": "human", "id": "a"}])
            self.assertNotEqual(b1["idempotency_key"], b2["idempotency_key"])
            self.assertTrue(l.flush(timeout=5))
            l.close()
        finally:
            srv.shutdown()

    def test_bad_request_dropped_not_retried_forever(self):
        srv = _server()
        try:
            l = Ledger("gate", url="http://127.0.0.1:%d" % srv.server_port,
                       spool_path=_tmp_spool(), flush_on_exit=False, base_retry_delay=0.05)
            l.record("t", {}, [{"kind": "human", "id": "bad"}])
            # A 400 is not retried; the sender drops it and the spool drains.
            self.assertTrue(l.flush(timeout=5))
            l.close()
        finally:
            srv.shutdown()

    def test_retries_with_backoff_then_succeeds(self):
        srv = _server()
        _H.fail_times = 2
        try:
            l = Ledger("gate", url="http://127.0.0.1:%d" % srv.server_port,
                       spool_path=_tmp_spool(), flush_on_exit=False,
                       base_retry_delay=0.05, max_retry_delay=0.2)
            l.record("gate.run.started", {}, [{"kind": "human", "id": "alice"}])
            self.assertTrue(l.flush(timeout=10))
            # 2 failures + 1 success = 3 POSTs for the same record.
            self.assertEqual(len(_H.seen), 3)
            l.close()
        finally:
            srv.shutdown()

    def test_spool_survives_restart_and_replays_in_order(self):
        spool_path = _tmp_spool()
        srv = _server()
        try:
            port = srv.server_port
            # Start disconnected (server not reachable at this URL) so records pile up in the
            # spool, then "restart" the client against the same spool path and let it drain.
            l1 = Ledger("gate", url="http://127.0.0.1:1", spool_path=spool_path, flush_on_exit=False,
                        base_retry_delay=0.05, max_retry_delay=0.1, timeout=0.3)
            l1.record("t", {"n": 1}, [{"kind": "human", "id": "a"}])
            l1.record("t", {"n": 2}, [{"kind": "human", "id": "a"}])
            l1.record("t", {"n": 3}, [{"kind": "human", "id": "a"}])
            time.sleep(0.3)
            self.assertEqual(l1.pending(), 3)
            l1.close()

            l2 = Ledger("gate", url="http://127.0.0.1:%d" % port, spool_path=spool_path,
                        flush_on_exit=False, base_retry_delay=0.05)
            self.assertTrue(l2.flush(timeout=5))
            self.assertEqual(len(_H.seen), 3)
            order = [b["payload"]["n"] for _, _, b in _H.seen]
            self.assertEqual(order, [1, 2, 3])
            l2.close()
        finally:
            srv.shutdown()

    def test_bounded_queue_drops_oldest(self):
        l = Ledger("gate", url="http://127.0.0.1:1", spool_path=_tmp_spool(), flush_on_exit=False,
                   max_queue=2, timeout=0.05, base_retry_delay=5, max_retry_delay=5)
        l.record("t", {"n": 1}, [{"kind": "human", "id": "a"}])
        l.record("t", {"n": 2}, [{"kind": "human", "id": "a"}])
        l.record("t", {"n": 3}, [{"kind": "human", "id": "a"}])
        time.sleep(0.05)
        self.assertLessEqual(l.pending(), 2)
        l.close()


class ActorChainTest(unittest.TestCase):
    def test_build_keeps_human_first(self):
        chain = actor_chain.build(
            actor_chain.human("alice"),
            actor_chain.agent("planner", model="gpt-5", model_version="1"),
        )
        self.assertEqual(chain[0], {"kind": "human", "id": "alice"})
        self.assertEqual(chain[1]["model"], "gpt-5")

    def test_build_rejects_non_human_first(self):
        with self.assertRaises(ValueError):
            actor_chain.build(actor_chain.agent("x"))

    def test_extend_appends_delegation_hop(self):
        chain = actor_chain.build(actor_chain.human("alice"))
        chain2 = actor_chain.extend(chain, actor_chain.service("scheduler"))
        self.assertEqual(len(chain2), 2)
        self.assertEqual(chain2[0]["kind"], "human")

    def test_extend_requires_human_first(self):
        with self.assertRaises(ValueError):
            actor_chain.extend([actor_chain.agent("x")], actor_chain.service("y"))


class VocabTest(unittest.TestCase):
    def test_names_match_shared_vocabulary(self):
        expected = {
            "ledger.goal.created", "ledger.step.planned", "ledger.action.attempted",
            "ledger.action.completed", "ledger.verification.recorded",
            "ledger.approval.requested", "ledger.approval.granted", "ledger.approval.denied",
            "ledger.budget.charged",
        }
        self.assertEqual(set(vocab.ALL), expected)


if __name__ == "__main__":
    unittest.main()
